[build]
    functions = "functions"
    publish = "build/"
    command = "npm run build"

[[redirects]]
    from = "/docs/*"
    status = 200
    force = true
    conditions = {Role = ["Employee", "Contractor", "Customer"]}

[[redirects]]
    from = "/docs/*"
    to = "/unauthorized"
    status = 401
    force = true
