[build]
    functions = "functions"
    publish = "build/"
    command = "npm run build"

[[redirects]]
    from = "/unauthorized"
    to = "/unauthorized.html"
    status = 200
    force = true

[[redirects]]
    from = "/login"
    to = "/.netlify/functions/login"
    status = 200
    force = true

[[redirects]]
    from = "/logout"
    to = "/.netlify/functions/logout"
    status = 200
    force = true

[[redirects]]
    from = "/callback"
    to = "/.netlify/functions/callback"
    status = 200
    force = true

[[redirects]]
    from = "/foo.html"
    to = "/foo.html"
    status = 200
    force = true
    conditions = {Role = ["authenticated"]}

[[redirects]]
    from = "/bar.html"
    to = "/bar.html"
    status = 200
    force = true
    conditions = {Role = []}

[[redirects]]
    from = "/bar.html"
    to = "/"
    status = 401
    force = true

[[redirects]]
    from = "/foo.html"
    to = "/"
    status = 401
    force = true

#[[redirects]]
#    from = "/*"
#    to = "/login"
#    status = 401
#    force = true
